server:
  port: 9000
spring:
  application:
    name: 'cards'
  profiles:
    active: 'prod'
  datasource:
    url: jdbc:mysql://192.168.1.5:3308/cardsdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: 'optional:configserver:http://192.168.1.5:8070/'

management:
  endpoints:
    web:
      exposure:
        include: '*'
